export const LOGOUT = 'LOGOUT';
export const LOGGED = 'LOGGED';

export const USERDATA_UPDATED = 'USERDATA_UPDATED';
export const USERDATA_RETRIEVED = 'USERDATA_RETRIEVED';

export const FETCH_AUTHORS_STARTED = 'FETCH_AUTHORS_STARTED';
export const FETCH_AUTHORS_COMPLETED = 'FETCH_AUTHORS_COMPLETED';
export const FETCH_AUTHORS_ERROR = 'FETCH_AUTHORS_ERROR';